### PR TITLE
Update upcoming events screen

### PR DESCRIPTION
**Pull request by jordanwade**
## DESCRIPTION
This PR improves the upcoming events screen. Screenshot below represents the changes.

### Screen captures of screen
iOS
https://v.usetapes.com/qEiAHMjUrm
Android
https://v.usetapes.com/mLtDEd658P

### What design trade-offs/decisions were made?
1. Font weight and colors are different from the Figma design to match the existing styles of the upcoming events on the main app screen. This should be flagged as an item to sync design and core

### How do I test this PR?
1. Go to main screen in app scroll down to "Here's what's coming up!" section
2. Click `View More`
3. See improved Upcoming Events screen.

## TODO:

- [x] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [x] No new warnings in tests, in storybook, and in-app
- [x] Upload GIF(s) of iOS and Android
- [x] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@jordanwade are you ready for me to review this :) ?

**Comment by jordanwade** [comment]
@vinnyjth not yet got some feedback from Michael so current making those changes. Is there a draft label or something I should put on this PR?

**Comment by vinnyjth** [comment]
@jordanwade Nope! You're good, I'll come review this as soon as you throw the 'ready to review' label on it

**Comment by vinnyjth** [comment]
Looking good on iOS and Android :D Nice work @jordanwade! We still need to tackle loading states for this, but we can do that in a fast follow PR.

**Pull request merged**
