### PR TITLE
Onboarding lock fields for existing users

### PR DESCRIPTION
**Pull request by vinnyjth**
## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [ ] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by vinnyjth** [comment]
@conrad-vanl Here's what I got so far. Work remaining to be done 

- Copy over ui-auth into Willow
- Update AuthSMSVerificationConnected to get `status` with Mutation
- Store the status in the store.
- If the status is
  - `EXISTING_USER`, skip onboarding
  - `NEW_USER_WITH_ROCK_PROFILE`, onboarding with locked fields
  -   `NEW_USER` onboarding with unlocked fields
- Add copy to direct users to logout and signup with Username/Password if they logged in as the wrong user

**Comment by conrad-vanl** [comment]
@vinnyjth bouncing this back to you to make sure it works. I _only_ implemented the `NEW_USER_WITH_ROCK_PROFILE` flow, as we still need to go through onboarding with `EXISTING_USER` to enable permissions, for now. We can improve this later.

Not sure best way to test, but you can see it working here, but I made this work by manually setting state:

https://www.loom.com/share/2c752498967f4695a83243259ce0d22c

**Comment by vinnyjth** [comment]
This looks awesome at a glance, but I'll test it best as I can and merge it. 

Heads up on `EXISTING_USER`, that field represents someone who has used the app in the past (they have successfully signed in with sms auth at least once before) so I think it's okay if we skip onboarding for those users.

**Comment by conrad-vanl** [comment]
@vinnyjth I don't think so. Onboarding still takes them through device-specific permissions, which you can't check from the backend.

**Comment by conrad-vanl** [comment]
Also, it looks like the back buttons in Auth don't work on this branch

**Comment by vinnyjth** [comment]
Good call with the `EXISTING_USER`, makes perfect sense. 

> Also, it looks like the back buttons in Auth don't work on this branch

They work, but they are the same color as the background 😬

**Comment by vinnyjth** [comment]
Tested and working @conrad-vanl. I was able to delete my `UserLogin` to mimic a `NEW_USER_WITH_PROFILE` and my fields were locked out as intended.

**Pull request merged**
