### PR TITLE
Equip the API to send universal sharing links

### PR DESCRIPTION
**Pull request by vinnyjth**
### What does this PR do, or why is it needed?

Adds "universal" sharing links to the app. Now sharing links will link to content in the app, or the app store itself if you don't have the app installed.

Screen Shot 2020-01-30 at 10 54 12 AM

## TODO:

- [ ] PR has a relevant title that will be understandable in a public changelog (ie...non developers)
- [ ] Closes [tag-issues-here]
- [ ] No new warnings in tests, in storybook, and in-app
- [ ] Upload GIF(s) of iOS and Android
- [ ] Set a relevant reviewer

## REVIEW:

**Manual QA**

- [x] Manual QA on iOS and ensure it looks/behaves as expected
- [ ] Manual QA on Android and ensure it looks/behaves as expected

**Code Review: Questions to consider**

- [ ] Read through the "Files changed" tab _very carefully_
- [ ] Edge cases: what assumptions are made about input?
- [ ] What kind of tests could be written?
- [ ] How might we make this easier for someone else to understand?
- [ ] Could the code be simpler?
- [ ] Will the code be easy to modify in the future?
- [ ] What's one part of these changes that makes you excited to merge it?

> The purpose of PR Review is to _improve the quality of the software._

### CODE REVIEW

**Comment by jordanwade** [comment]
Looks like this working correctly on iOS. Seems to have some trouble with an Android simulator. Going to try it on a physical device instead.

**Comment by vinnyjth** [comment]
Interesting! In what way is it not working? The sharing links seem to be working for me on the Android sim, but I could be missing something :)

**Comment by jordanwade** [comment]
@vinnyjth it looks like it just redirects to the play store even with the Willow app installed on the sim. It probably just something wrong with my local setup. Going to try my physical Android device shortly.

**Comment by vinnyjth** [comment]
@jordanwade Gotcha. The whole "deep linking" was setup in a different PR, this PR is just the generation of the links themselves. You MIGHT need to have additional configuration for Android deep links to work locally (either in the sim or on an actual device). I'm trying to remember what that is....

**Comment by vinnyjth** [comment]
Edit: are you building with they `keystore`?

If the sharing links are working correctly, I think this is GTG and we can debug further issues in master :D

**Pull request merged**
